### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by vlebourl** [borpin/vesync-bpo#1]
Hey, 
Didn't know how get in contact with you so here I go :)
I just acquired a Dual200S so took a look at your component. I forked and already made a few technical changes, mainly making it installable through hacs. Let me know if you're interested in merging that or if I keep it for my own. Great work anyways! 
Cheers

**Comment by borpin** [comment]
Thanks.  The idea for me is that anything done can be merged into the main integration so I'd rather keep the HACS separate, however, very interested in what you had to do to enable it for HACS.

My Python skills are a bit thin, but I understand systems and other programming languages!

If you have any general changes, then feel free to contribute. I aim to feed this back in once the PR that is in train has been merged to core.

**Comment by vlebourl** [comment]
core merging is sometimes very long... i'm on the tahoma/overkiz team, it's finally moving on but it took very long...
Integrating hacs is done by moving everything to the `custom_components/vesync2/` folder, and adding the `hacs.json` file.
I'll keep the hacs version independent then, and merge in your progress. I chose to move to a local version of pyvesync to be able to easily fix it as well if needed. I'll propagate any impacting change I might do. 
Cheers!

**Comment by borpin** [comment]
Yes it can take a while!

> I chose to move to a local version of pyvesync to be able to easily fix it as well if needed.

Yes, I noted that. The author of that library is quite responsive right now so anything you find I think he will include quite quickly.

> I'll propagate any impacting change I might do.

Ok, great :)

**Comment by vlebourl** [comment]
another benefit of the hacs setup, is that the component as will be committed to core resides in its own folder (here custom_components/vesync2), which allows for easy pre-commit hooks, workflow, requirements and all other tools that can help in the code quality, and to respect core's style and standards!

**Comment by borpin** [comment]
Ah interesting I din't know that. You seem pretty knowledgeable about this stuff.

So converting it to HACS compatible, has no downsides? How does HACS handle different branches?

I 'own' another integration, emoncms. I'd like to get it updated so it can be configured from the UI but have no idea where to start.

**Comment by vlebourl** [comment]
configuration from the UI is done in the config_flow file.
hacs installation is the main branch. Best practice is to have releases when enough changes have been made. Otherwise, commit hash serve as version number. 
So what I usually do is work on a dev branch, PR into main and draft a new release. 
I mentionned the style earlier because core team is very picky regarding style and code standards.

**Comment by borpin** [comment]
> hacs installation is the main branch. Best practice is to have releases when enough changes have been made.

But how do you test it as you are working on the integration.

> I mentioned the style earlier because core team is very picky regarding style and code standards.

Which is a good thing, but my lack of Python experience then works against me. As long as I have something good to copy and extend, I'm OK (like this integration). So adding new sensors, I can work through. Something new and I'm pretty lost.

> configuration from the UI is done in the config_flow file.

Trouble is the emoncms integration is pretty old and I really have no idea where to start.

**Comment by vlebourl** [comment]
To test, I start a temporary new HA instance dedicated to it. Then when good enough, I merge into main.

**Comment by vlebourl** [comment]
I already made a lot of improvement, I'll try to prepare a PR for you!

**Comment by gdgib** [comment]
@borpin and @vlebourl not to dredge up too old an issue, but I thought it **might** get your attention.

You both did excellent work on this code.   As I try to set up https://github.com/haext/custom_vesync, which will ideally have multiple maintainers, I noticed neither of you attached a license to your code.  It seems clear from context that you intended people to use your work, but without an explicit license, there's some legal risk for those us who want to extend and use your code.  In https://github.com/haext/custom_vesync/pull/22 I'm proposing to use the Apache-2.0 license going forward.  Would you both be so kind as to comment on that PR if you're willing to put your work under the Apache-2.0?

For what it's worth, MIT, BSD3, or CC-BY are also excellent for this kind of code if you prefer one of them.  I prefer Apache-2.0 because it's much better written.  If you want to learn about licenses, I can recommend https://choosealicense.com/ and https://choosealicense.com/appendix/, and I'm happy to help personally.

Thanks for your help, and for your code.  I hope to hear from you soon!
